"""empty message

Revision ID: 06099c893342
Revises: 36369740878d
Create Date: 2023-08-24 10:29:07.468538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06099c893342"
down_revision = "36369740878d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
